### ISSUE TITLE
problem in parsing the config file on fire-fly

### ISSUE THREAD

**Issue by tommasopolonelli** [aerosense-ai/data-gateway#121]
root@001360e3d3c0:/usr/aerosense/data-gateway# gateway start --save-local-logs
Traceback (most recent call last):
  File "/usr/local/bin/gateway", line 8, in <module>
    sys.exit(gateway_cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/aerosense/data-gateway/data_gateway/cli.py", line 178, in start
    data_gateway = DataGateway(
  File "/usr/aerosense/data-gateway/data_gateway/data_gateway.py", line 91, in __init__
    packet_reader_configuration = self._load_configuration(configuration_path=configuration_path)
  File "/usr/aerosense/data-gateway/data_gateway/data_gateway.py", line 190, in _load_configuration
    configuration = Configuration.from_dict(json.load(f))
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 12 column 3 (char 292)

**Comment by tommasopolonelli** [comment]
Thanks!

**Comment by tommasopolonelli** [comment]
Hi, @thclark , we were testing IMUs and Baros together for 2 nodes from the gateway and we notice several problems. It would be nice if we can have another meeting to discuss the issues. Please, let me know when you are free.
