### ISSUE TITLE
 KeyError in file_handler, while running ingress-eu cloud fiunction

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#9]
## Bug report

There seems to be a problem with cloud function that gets window from the ingress bucket.

### What is the current behavior?

```
{
  "textPayload": "Traceback (most recent call last):\n  File \"/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py\", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py\", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File \"/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py\", line 171, in view_func\n    function(data, context)\n  File \"/workspace/main.py\", line 38, in clean_and_upload_window\n    window, window_metadata = window_handler.get_window()\n  File \"/workspace/window_handler.py\", line 73, in get_window\n    window_metadata = cloud_metadata[\"custom_metadata\"][\"data_gateway__configuration\"]\nKeyError: 'data_gateway__configuration'",
  "insertId": "000001-d74b9c37-a87c-4ad4-8879-37c0b2397de0",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "aerosense-twined",
      "function_name": "ingress-eu",
      "region": "europe-west6"
    }
  },
  "timestamp": "2021-12-11T12:54:03.594Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "22ajl43qdhwi"
  },
  "logName": "projects/aerosense-twined/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/aerosense-twined/traces/62cd5c882711eaae92ff91fb8fd7a643",
  "receiveTimestamp": "2021-12-11T12:54:04.565208817Z"
}
```
Traceback:
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 38, in clean_and_upload_window
    window, window_metadata = window_handler.get_window()
  File "/workspace/window_handler.py", line 73, in get_window
    window_metadata = cloud_metadata["custom_metadata"]["data_gateway__configuration"]
KeyError: 'data_gateway__configuration'
```

### Your environment

  - Library Version: `0.7.4` #8

**Comment by time-trader** [comment]
@cortadocodes The error still persists in version 0.11.4: 

```
 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 38, in upload_window
    window, window_metadata = window_handler.get_window()
  File "/workspace/window_handler.py", line 72, in get_window
    window_metadata = cloud_metadata["custom_metadata"]["data_gateway__configuration"]
KeyError: 'data_gateway__configuration'
```

Occurs once per gateway start with cloud upload. (In the beginning of execution)

**Comment by cortadocodes** [comment]
I think this is probably the configuration file itself being uploaded without metadata - because it doesn't require it. I'll remove the upload of configuration as a file as its included in every datafile's metadata.

**Comment by time-trader** [comment]
The issue still persists in the recent gateway testing:

Reviewing the gateway logs, it seems to be trigger once gateway re-establishes the connection (Updates handles)..

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 38, in upload_window
    window, window_metadata = window_handler.get_window()
  File "/workspace/window_handler.py", line 72, in get_window
    window_metadata = cloud_metadata["custom_metadata"]["data_gateway__configuration"]
KeyError: 'data_gateway__configuration'
```
